// All user-facing terminology lives here.
// Renaming any concept requires changing only this file — no logic changes.

const COLLECTION = 'Endeavour';
const COLLECTION_PLURAL = 'Endeavours';

export const LABELS = {
  collection:       COLLECTION,
  collectionPlural: COLLECTION_PLURAL,
  noCollection:     `No ${COLLECTION}`,
  addToCollection:  `Add to ${COLLECTION}:`,
  noneInCollection: (things: string) => `No ${things} in this ${COLLECTION}`,
  quickAccessPlaceholder: `Jump to a note, task, list, tracker, routine, schedule, or ${COLLECTION}…`,
  quickAccessScheduleHidden: 'Hidden',
  collectionFilterHint:  `Expand ${COLLECTION} filter`,
  collectionKind: {
    project: 'Project',
    list:    'List',
    tracker: 'Tracker',
    routine: 'Routine',
  },
  taskKind: {
    action:    'Action',
    waiting:   'Waiting',
    milestone: 'Milestone',
  },
  milestoneDate: 'Milestone date',
  scheduledFor:  'Scheduled',

  // Voice dictation (src/services/speech/, src/components/VoiceIndicator/). `errors` is keyed
  // by SpeechErrorCode.
  voice: {
    listening:    'Listening…',
    transcribing: 'Transcribing…',
    stopHint:     (hotkey: string) => `${hotkey} or Enter to finish · Esc to cancel`,
    noTarget:     'Click into a text field first, then start dictation.',
    done:         'Finish',
    cancel:       'Cancel',
    errors: {
      'signed-out':      'Sign in to use voice dictation.',
      'limit-reached':   'Monthly dictation limit reached.',
      'not-configured':  'Voice dictation isn\'t set up on the server yet.',
      unavailable:       'Couldn\'t reach the speech service.',
      'mic-denied':      'Microphone access was blocked.',
      'mic-unavailable': 'No microphone was found.',
      failed:            'Couldn\'t transcribe that.',
    } as Record<string, string>,
  },

  // Local storage limits — see utils/persistStorage.ts and Settings → Storage.
  storage: {
    keyNames: {
      'todo-app-storage':      'Tasks',
      'todo-calendar':         'Calendar',
      'todo-schedules':        'Schedules',
      'todo-tracker':          'Records',
      'todo-routines':         'Routines',
      'notes-storage':         'Notes',
      'lists-storage':         'Lists',
      'fitness-storage':       'Fitness',
      'todo-portfolio':        'Portfolio',
      'todo-settings':         'Settings',
      'todo-notifications':    'Notifications',
      'todo-recent-items':     'Quick Access history',
      'todo-hotkey-overrides': 'Keyboard shortcuts',
      'todo-ui-session':       'Session',
      'agent-log':             'Assistant activity log',
      'agent-batches':         'Assistant undo history',
      'trash-storage':         'Recycling Bin',
    } as Record<string, string>,
    fullTitle:   'Storage on this device is full',
    fullMessage: (biggest: string) => `Your latest changes can't be saved on this device any more, so they'll be lost if you close the app — nothing is lost while it stays open, and if you're signed in they still sync to your account. ${biggest} Open Settings → Storage to see what is using the space.`.replace('  ', ' '),
    saveFailedTitle:   "Changes couldn't be saved",
    saveFailedMessage: "Your latest changes couldn't be saved on this device, so they'll be lost if you close the app. If you're signed in they still sync to your account. Try exporting a backup (Account → Export).",
    section:     'Storage',
    usageName:   'Used on this device',
    usageDesc:   "Most data lives in the browser's local storage, which allows roughly 5 MB in total. Notes are kept in a separate database with far more room. Sizes are approximate.",
    inDatabase:  'database',
    shrinkName:  'Shrink images in notes',
    shrinkDesc:  'Recompresses large pasted images (to fit 1600 px) in every note and tab. Text is untouched; the image quality on screen stays good. The open note is closed first.',
    shrinkButton: 'Shrink images',
    shrinking:   'Shrinking…',
    shrinkNothing: 'No large images found.',
    shrinkDone:  (images: number, notes: number, saved: string) => `Shrank ${images} image${images === 1 ? '' : 's'} in ${notes} note${notes === 1 ? '' : 's'}, freeing about ${saved}.`,
  },

  // The "Linked from" bar in a note and its remove-link prompt: src/components/NoteEditor/NoteBacklinks.tsx.
  noteBacklinks: {
    linkedFrom:      'Linked from',
    open:            'Open',
    insert:          'Insert into the note at the cursor as a link',
    remove:          'Remove this link',
    otherTabs:       'On other tabs',
    goToTab:         (tab: string) => `Go to the "${tab}" tab`,
    chipTitleOtherTabs: (here: number, elsewhere: number) => `${here} on this tab, ${elsewhere} on other tabs`,
    removeTitle:     'Remove the link too?',
    removeMessage:   (noun: string) => `You removed the text that linked to this ${noun}. Remove the link entirely, or keep it in this note's "Linked from" list?`,
    removeConfirm:   'Remove link entirely',
    keepLink:        'Keep link',
  },

  // Inline objects in notes: type \ to create something as you write (components/NoteEditor/objects/).
  noteObjects: {
    task:          'Task',
    pickHint:      'Tab or Enter to choose · Esc to keep a plain \\',
    newKind:       (label: string) => `New ${label.toLowerCase()}`,
    composeHint:   'Tab: edit · Esc: cancel',
    create:        'Create',
    moreOptions:   'All options',
    invalidField:  (label: string) => `Couldn't read the ${label.toLowerCase()} — try "fri", "12 oct" or "5pm"`,
    created:       (label: string) => `${label} created`,
    open:          'Open',
    undo:          'Undo',
    toolbarButton: 'Create a reminder (or another object) as you type — or just type \\',
    reminder: {
      hint:             'Nudge me at a time — "call mum tomorrow 5pm"',
      fieldTitle:       'What',
      fieldDate:        'Date',
      fieldTime:        'Time',
      titlePlaceholder: 'What to be reminded about',
      datePlaceholder:  'Today',
      timePlaceholder:  'All day',
      needsTitle:       'Type what to be reminded about first',
    },
    deadline: {
      hint:             'Something due by a time — "essay due fri 5pm"',
      fieldTitle:       'What',
      fieldDate:        'Due',
      fieldTime:        'By',
      titlePlaceholder: 'What is due',
      datePlaceholder:  'Today',
      timePlaceholder:  'End of the day',
      needsTitle:       'Type what is due first',
    },
    event: {
      hint:             'Something on at a time — "lunch with Sam fri 1-2pm"',
      fieldTitle:       'What',
      fieldDate:        'Date',
      fieldTime:        'Time',
      fieldWhere:       'Where',
      titlePlaceholder: 'What it is',
      datePlaceholder:  'Today',
      timePlaceholder:  'All day',
      wherePlaceholder: 'A place or a meeting link',
      needsTitle:       'Type what the event is first',
    },
    // An item's flags and repeat (the object's right-click menu).
    card: {
      repeat:     'Repeat',
      repeatNone: 'Doesn’t repeat',
      repeatFreq: { daily: 'Every day', weekly: 'Every week', monthly: 'Every month', yearly: 'Every year' },
      important:  'Important',
      tentative:  'Tentative',
      stopRepeatTitle:   'Stop repeating?',
      stopRepeatMessage: (rule: string, first: string) => `It repeats ${rule.toLowerCase()}. Only the first one, ${first}, will stay; every other date in the series comes off your calendar.`,
      stopRepeatConfirm: 'Stop repeating',
    },
    // The expanded pane's body (objects/ObjectBody.tsx): no field labels, so these are hints only.
    body: {
      notesPlaceholder: 'Notes…',
      editNotes:        'Click to edit',
      addNotes:         '+ Notes',
      addLink:          '+ Link',
      linkPlaceholder:  'Paste a link, Enter to add',
      removeLink:       'Remove this link',
      addEndeavour:     '+ ' + COLLECTION,
      changeEndeavour:  'Change the ' + COLLECTION.toLowerCase(),
      noBody:           'Open ↗ to see everything about it.',
      // Options that are off show greyed; a click turns them on.
      turnOn:           (label: string) => `Turn on: ${label}`,
      repeatHow:        'Repeat how often?',
      addPlace:         '+ Place',
      placePlaceholder: 'A place or a meeting link, Enter to save',
      editPlace:        'Click to change the place',
      openPlace:        'Open the meeting link',
      notifyMe:         'Notify me',
      notifyTitle:      'When to be notified — click to change',
      notifyOff:        'Off',
      notifyDone:       'Done',
      notifyUnits:      { minutes: 'minutes', hours: 'hours', days: 'days' },
      notifyBefore:     (value: number, unit: string) => `${value} ${unit} before`,
      notifyDays:       (days: number, at: string) => `${days === 0 ? 'On the day' : days === 1 ? '1 day before' : `${days} days before`}, ${at}`,
    },
    // How linked text shows the item it links to (an inline pane, expanded into a box).
    link: {
      open:        'Open',
      markDone:    'Mark done',
      doneHint:    'Mark done (or untick)',
      markNotDone: 'Mark not done',
      unlink:      'Unlink',
      deleted:     'Deleted',
      missing:     'Deleted — restore it from the Recycling Bin to bring the link back',
      done:        'Done',
      overdue:     'Overdue',
      archived:    'Archived',
      repeats:     'Repeats',
      iconTitle:   (kind: string, summary: string) => `${kind}: ${summary}`,
      showDetails: 'Show all details',
      hideDetails: 'Hide details',
      seeDates:    'See its dates',
      series:      'Repeats',
      openSeries:  'Open the series',
      openThisOne: 'Open this one in the calendar',
      nextOne:     'next',
      removeOption: (label: string) => `${label} — click to remove`,
      editDate:    'Change the date',
      editTime:    'Change the time (empty = all day)',
      datePlaceholder: 'fri, 12 oct…',
      timePlaceholder: '5pm, 17:30…',
      addTime:     '+ time',
    },
  },

  // Shared by every item pane that can be archived/deleted (Task, Calendar event, Calendar
  // reminder — and future apps): see src/components/ItemActions/.
  itemActions: {
    archive:           'Archive',
    restore:           'Restore',
    complete:          'Complete',
    reopen:            'Mark incomplete',
    markDone:          'Mark done',   // a Reminder/Deadline occurrence (doneDates)
    notDone:           'Not done',
    archivedGroup:     'Archived',
    reasonLabel:       'Why are you archiving it? (optional)',
    reasonPlaceholder: 'e.g. No longer relevant, replaced by something else, decided not to do it…',
    reasonHeading:     'Reason',
    archiveTitle:      (noun: string) => `Archive this ${noun}?`,
    archiveHint:       (hiddenFrom: string) => `It leaves ${hiddenFrom} but is kept, and you can restore it any time.`,
    deleteTitle:       (noun: string) => `Delete this ${noun} permanently?`,
    deleteWarning:     'This cannot be undone.',
    deleteSafeHint:    'Not sure? Archiving keeps it out of the way without losing it.',
    deleteConfirm:     'Delete permanently',
    archiveInstead:    'Archive instead',
  },

  // A row's own actions (components/RowHoverActions/RowAction): the hover tooltip on desktop,
  // the visible label in the long-press sheet on Android.
  // Right-click menus (src/contextMenu/, CLAUDE.md "Right-click menus").
  contextMenu: {
    cut:          'Cut',
    copy:         'Copy',
    paste:        'Paste',
    pastePlain:   'Paste as plain text',
    selectAll:    'Select all',
    link:         'Link…',
    createFrom:   'Create from selection…',
    style:        'Style',
    title:        'Title',
    heading:      (level: number) => `Heading ${level}`,
    normalText:   'Normal text',
    clipboardBlocked: 'The clipboard couldn’t be read here (the browser may have blocked access). Use Ctrl+V, or Ctrl+Shift+V for plain text.',
    openNote:     'Open',
    noteDetails:  'Edit details',
  },

  // The "what are you creating?" switcher at the top of a creation pane (config/createKinds.ts),
  // and the New notebook pane's parent picker.
  createKinds: {
    switcherAria: 'What to create',
    note:         'Note',
    notebook:     'Notebook',
    noteTag:      'Tag',
  },
  notebookParent: {
    label:       'Inside',
    topLevel:    'Top level (no parent)',
    change:      'Change where this notebook goes',
    makeTopLevel: 'Make it a top-level notebook',
  },

  rowActions: {
    edit:       'Edit',
    delete:     'Delete',
    archive:    'Archive',
    restore:    'Restore',
    addSection: 'Add section',
    indent:     'Make sub-section of the one above',
    indentNote: 'Make sub-note of the one above',
    outdent:    'Move up one level',
    editThing:   (noun: string) => `Edit ${noun.toLowerCase()}`,
    deleteThing: (noun: string) => `Delete ${noun.toLowerCase()}`,
    options:     (name: string) => `Options for “${name}”`,
  },

  // Swipe-left on a row (Android, docs/android/11 §9): act at once, offer Undo.
  swipeActions: {
    archive:       'Archive',
    delete:        'Delete',
    archivedToast: (title: string) => `Archived “${title}”`,
    deletedToast:  (title: string) => `Deleted “${title}”`,
    undo:          'Undo',
  },

  // Suite-wide Recycling Bin — see src/services/trash.ts, src/services/trashCapture.ts,
  // src/components/RecyclingBinPane/.
  recyclingBin: {
    title:            'Recycling Bin',
    openFromAccount:  'Recycling Bin',
    filterAll:        'All',
    empty:            'The recycling bin is empty.',
    emptyFiltered:    (section: string) => `Nothing from ${section} in the recycling bin.`,
    deletedByYou:     'by You',
    restore:          'Restore',
    deleteForever:    'Delete forever',
    emptyBinButton:   'Empty recycling bin',
    emptyBinTitle:    'Empty the recycling bin?',
    emptyBinMessage:  'Everything in the recycling bin will be permanently deleted.',
    emptyBinConfirm:  'Empty bin',
  },

  // In-app replacement for window.confirm()/alert() — see components/ConfirmDialog
  dialogs: {
    confirm:    'Confirm',
    cancel:     'Cancel',
    ok:         'OK',
    alertTitle: 'Something went wrong',
  },

  errorBoundary: {
    appTitle:       'Something went wrong',
    appMessage:     "The app hit an unexpected error and couldn't continue. Your data is still saved on this device. Reloading usually fixes it; if it keeps happening, export a backup first.",
    sectionTitle:   (section: string) => `${section} hit an error`,
    sectionMessage: "This section couldn't be shown. The rest of the app still works — switch to another section, or try again.",
    reload:         'Reload',
    reloadSection:  'Reload this section',
    exportBackup:   'Export backup',
    backupFailed:   "Couldn't export a backup.",
    details:        'Details',
  },

  signOut: {
    title:         'Sign out?',
    message:       "Your tasks, calendar, records, lists, notes and portfolio are removed from this device when you sign out. They stay in your account and come back when you sign in.",
    keptOnDevice:  "Kept on this device, because they aren't saved to your account yet: Fitness activities and activity types, routine check-off history, and your settings.",
    confirm:       'Sign out',
    unsavedTitle:  "Some changes couldn't be saved",
    unsavedMessage: (reason: string) => `Your latest changes couldn't be saved to your account (${reason}). Signing out now will discard anything that hasn't been saved.`,
    unsavedConfirm: 'Sign out and discard',
  },

  // Returning to the Android app from a provider's sign-in page (services/oauthState.ts)
  oauthReturn: {
    provider:  { strava: 'Strava', 'google-calendar': 'Google Calendar' },
    connected: (provider: string) => `${provider} connected`,
    failed:    (provider: string) => `${provider} connection failed`,
  },

  // Notifications on Android (services/notifications/androidScheduler.ts) and Settings → Notifications
  notifications: {
    channels: {
      reminders: { name: 'Reminders & deadlines', description: 'Reminders, deadlines and task deadlines' },
      events:    { name: 'Events', description: 'Calendar events and committed schedule blocks' },
      important: { name: 'Important', description: 'Anything flagged important' },
    },
    // The bell's cards (NotificationCenter) — see services/notifications/actions.ts for what each does.
    card: {
      gotIt:          'Got it',
      gotItHint:      'Noted — it won’t notify again, on any device',
      gotItReminder:  'Noted — marks this reminder done, on every device',
      done:           'Done',
      doneHint:       'The work is done — struck out on the calendar',
      snooze:         'Snooze',
      postpone:       'Postpone',
      archive:        'Archive',
      open:           'Open',
      ok:             'OK',
      cancel:         'Cancel',
      snoozeTitle:    'Remind me again',
      snooze10m:      'In 10 min',
      snooze1h:       'In 1 hour',
      snoozeEvening:  'This evening',
      snoozeMorning:  'Tomorrow morning',
      snoozeIn:       'In',
      set:            'Set',
      postponeTitle:  'Move it to',
      postponeTomorrow: 'Tomorrow',
      postponeNextWeek: 'Next week',
      postponeOnlyThis: 'Only this date moves; the rest of the series stays',
      move:           'Move',
      moved:          (title: string, when: string) => `Moved “${title}” to ${when}`,
      archiveTitle:   'Archive this date',
      archiveSeries:  'Archive the whole series',
      archived:       (title: string) => `Archived “${title}”`,
      undo:           'Undo',
      clearAll:       'Clear all',
      clearAllHint:   'Empties the bell on this device only',
    },
    actions: {
      done:         'Got it',
      complete:     'Complete',
      snooze10m:    '10 min',
      snooze1h:     '1 hour',
      snoozeMorning: 'Tomorrow',
    },
    permission: {
      title:   'Get a nudge when things are due?',
      message: 'Reminders, deadlines and events can notify you on this phone even when the app is closed.',
      confirm: 'Turn on',
      exactTitle:   'Let reminders arrive on time?',
      exactMessage: 'Android delays notifications unless the app may set exact alarms. The next screen lets you allow it.',
      exactConfirm: 'Open settings',
    },
    settings: {
      heading:        'Notifications',
      status:         'Notifications',
      statusOn:       'On',
      statusOff:      'Off — allow them in Android settings',
      statusAsk:      'Not set up yet',
      turnOn:         'Turn on',
      exact:          'Exact timing',
      exactOn:        'Allowed',
      exactOff:       'Not allowed — reminders may arrive late',
      exactFix:       'Allow',
      reminders:      'Reminders & deadlines',
      events:         'Events & schedules',
      morning:        '“Tomorrow” snooze time',
      evening:        '“This evening” snooze time',
      quiet:          'Quiet hours',
      quietHint:      'Nothing arrives in these hours except items flagged important; the rest waits until they end.',
      quietFrom:      'From',
      quietTo:        'to',
      battery:        'If notifications stop arriving, set this app’s battery use to “Unrestricted” in Android settings.',
      test:           'Send a test notification',
      testTitle:      'Test notification',
      testBody:       'Notifications are working.',
    },
  },

  // Calendar
  // A date taken out of a repeating series, still linked to it (services/calendarSeries.ts).
  calendarSeries: {
    partOf:               (date: string) => `Part of a repeating series — stands in for its ${date}`,
    partOfTail:           (date: string) => `Continues a repeating series from ${date}`,
    seriesGone:           'Was part of a repeating series that has been deleted',
    openSeries:           'Open the series',
    unlink:               'Unlink from the series',
    unlinkHint:           'Keep this as it is, no longer part of the series',
    changed:              'changed',
    deleteChangedTitle:   (n: number) => `Also delete ${n === 1 ? 'the date' : `the ${n} dates`} changed separately?`,
    deleteChangedMessage: (n: number) => `${n === 1 ? 'One date was' : `${n} dates were`} taken out of this series and edited on ${n === 1 ? 'its' : 'their'} own. Delete ${n === 1 ? 'it' : 'them'} too, or keep ${n === 1 ? 'it' : 'them'} as separate items?`,
    deleteChangedConfirm: 'Delete them too',
    keepChanged:          'Keep them',
  },
  calendarItemKind: {
    event:    'Event',
    reminder: 'Reminder',
    deadline: 'Deadline',
  },
  calendarEventType: {
    default:  'Event',
    birthday: 'Birthday',
    travel:   'Travel',
  },

  // Records / Trackers
  records: 'Records',
  tracker: 'Tracker',
  trackerPlural: 'Trackers',
  trackerEntry: 'Entry',
  trackerEntryPlural: 'Entries',

  // Routines
  routine: 'Routine',
  routinePlural: 'Routines',

  // Schedules (recurring weekly timetables, Calendar section)
  schedule: 'Schedule',

  // Lists
  list:          'List',
  listPlural:    'Lists',
  listItem:      'Item',
  listItemPlural:'Items',
  listType:      'List Type',
  // Per ListKind: `one` names a single list of that kind, `many` heads its group in the sidebar
  // and the create-list type picker.
  listKind: {
    checklist: { one: 'Checklist',      many: 'Checklists' },
    watchlist: { one: 'Watchlist',      many: 'Watchlists' },
    reference: { one: 'Reference list', many: 'Reference' },
  },
  checklist: {
    addPlaceholder: 'Add an item…',
    clearChecked:   'Clear checked',
    uncheckAll:     'Untick all',
    empty:          'Nothing on this list yet',
    reusable:       'Reusable',
    reusableHint:   'Untick everything when a linked task is completed, so the list is ready for next time.',
  },

  // Links between lists and tasks / calendar items / notes (services/taskListLinks.ts)
  listLinks: {
    linkList:        '+ List',
    linkNote:        '+ Note',
    linkedFrom:      'Linked from',
    notesLabel:      'Notes',
    pickerTitle:     'Link a list',
    pickerSearch:    'Search lists…',
    pickerEmpty:     'No lists match',
    completeTitle:   (task: string) => `Complete “${task}”?`,
    completeMessage: (list: string) => `Everything on ${list} is ticked off.`,
    completeReset:   'The list will be unticked, ready for next time.',
    completeConfirm: 'Complete task',
    completeCancel:  'Not yet',
  },

  // Every "link a …" picker (utils/suggestRank.ts).
  pickers: {
    suggestedFrom: (words: string[]) => `Suggested from “${words.join(', ')}”`,
    recent:        'Recent',
  },

  // Overview — the suite-level section (src/overview/, components/OverviewSection/).
  overview: {
    savedOne:          'Saved overview',
    endeavoursHeading: COLLECTION_PLURAL,
    savedHeading:      'My overviews',
    newOverview:       '+ New overview',
    noSaved:           'None yet — make one to gather things from every app.',
    pickHint:          `Pick a ${COLLECTION.toLowerCase()} for everything about it, or one of your saved overviews.`,
    newTitle:          'New overview',
    editTitle:         'Edit overview',
    endeavourTitle:    (name: string) => `Everything for ${name}`,
    openInOverview:    'Overview',
    name:              'Name',
    namePlaceholder:   'e.g. Due this fortnight',
    sourcesLabel:      'Include',
    sourcesAll:        'Everything',
    endeavourLabel:    COLLECTION,
    anyEndeavour:      `Any ${COLLECTION.toLowerCase()}`,
    statusLabel:       'Show',
    whenLabel:         'Dates',
    windowLabel:       'Within (days)',
    searchLabel:       'Title contains',
    sortLabel:         'Sort',
    groupLabel:        'Group by',
    save:              'Save overview',
    create:            'Create overview',
    edit:              'Edit',
    deleteNoun:        'overview',
    sources: {
      task:         'Tasks',
      event:        'Events',
      reminder:     'Reminders',
      deadline:     'Deadlines',
      note:         'Notes',
      list:         'Lists',
      listItem:     'List items',
      trackerEntry: 'Tracker entries',
    },
    status:       { open: 'Open', done: 'Done', past: 'Past', archived: 'Archived' },
    statusFilter: { open: 'Open only', all: 'Open and done' },
    whenFilter:   { any: 'Any date', dated: 'Has a date', upcoming: 'Upcoming', past: 'Past' },
    sort:         { 'when-asc': 'Date (soonest first)', 'when-desc': 'Date (latest first)', title: 'Title', source: 'App' },
    groupBy:      { none: 'Nothing', source: 'App', endeavour: COLLECTION, month: 'Month' },
    columns:      { what: 'What', when: 'When', status: 'Status', from: 'From', endeavour: COLLECTION },
    noDate:       '—',
    noEndeavour:  `No ${COLLECTION.toLowerCase()}`,
    noRows:       'Nothing matches.',
    count:        (n: number) => `${n} item${n === 1 ? '' : 's'}`,
    lockedHidden: (n: number) => `${n} item${n === 1 ? '' : 's'} in locked notes or lists hidden`,
  },

  // Links between tasks — see config/itemLinkKinds.ts. `out` = how the owning task reads it
  // ("Waiting on: X"), `in` = how the other task reads it ("Unlocks: Y").
  taskLinks: {
    heading:         'Task links',
    kinds: {
      dependsOn:  { out: 'Waiting on',  in: 'Unlocks' },
      followUpOf: { out: 'Follow-up of', in: 'Led to' },
      related:    { out: 'Related',     in: 'Related' },
    },
    addDependsOn:    '+ Waiting on…',
    addRelated:      '+ Related…',
    addFollowUp:     '+ Follow-up',
    reasonPlaceholder: 'Reason (optional)',
    removeLink:      'Remove link',
    pickerTitle:     'Link a task',
    pickerSearch:    'Search tasks…',
    pickerEmpty:     'No tasks match',
    blockedPill:     (n: number) => `waits on ${n}`,
    blockedTitle:    (titles: string[]) => `Waiting on: ${titles.join(', ')}`,
    blockedGroup:    'Waiting on other tasks',
    followUpBanner:  (origin: string) => `Follow-up of “${origin}”`,
    rejected: {
      self:      'A task can’t be linked to itself.',
      duplicate: 'These tasks are already linked that way.',
      cycle:     'That would make the tasks wait on each other in a loop.',
      missing:   'That task no longer exists.',
      hierarchy: 'A task’s own parent and sub-tasks are already connected to it.',
    },
    completeBlockedTitle:   (task: string) => `Complete “${task}”?`,
    completeBlockedMessage: (titles: string[]) => `It’s still waiting on: ${titles.join(', ')}.`,
    completeAnyway:         'Complete anyway',
    completeAll:            (n: number) => `Complete all ${n + 1}`,
    toastCompleted:  (task: string) => `Completed “${task}”`,
    toastUnlocked:   (titles: string[]) => `Unlocked: ${titles.join(', ')}`,
    toastFollowUp:   '+ Follow-up',
    toastUndo:       'Undo',
    // Hovering a task's Complete button (services/taskCompletion.ts taskCompletionOptions).
    menu: {
      completeWithFollowUp: 'Complete + add follow-up',
      completeWithBlockers: (n: number) => `Complete, with the ${n} it’s waiting on`,
      followUpOnly:         'Add a follow-up (keep this open)',
    },
  },

  views: {
    overview:  'Overview',
    tasks:     'Tasks',
    calendar:  'Calendar',
    records:   'Records',
    lists:     'Lists',
    portfolio: 'Portfolio',
    notes:     'Notes',
    fitness:   'Fitness',
  },

  // Portfolio
  portfolio:           'Portfolio',
  watchlist:           'Watchlist',
  watchlistItem:       'Ticker',
  watchlistItemPlural: 'Tickers',
  portfolioTag:        'Tag',
  investmentPurpose:   'Investment Purpose',

  // Fitness
  fitness:         'Fitness',
  activity:        'Activity',
  activityPlural:  'Activities',
} as const;
